name: CI
on: [push, pull_request]

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v1
        with:
          go-version: 1.14

      - run: make format

      - uses: actions-contrib/golangci-lint@v1
        env:
          GOROOT: ""
        with:
          args: "run"

      - run: make test

      - run: make build

  deploy:
    name: Deploy
    needs: [check]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v1
        with:
          go-version: 1.14

      - uses: actions/setup-node@v1
        with:
          node-version: "14.x"

      - run: make install

      - run: make build

      - run: make deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
