name: Deploy
on:
  push:
    branches:
      - master

env:
  AIRTABLE_BASE: ${{ secrets.AIRTABLE_BASE }}
  AIRTABLE_KEY: ${{ secrets.AIRTABLE_KEY }}
  AIRTABLE_TABLE: ${{ secrets.AIRTABLE_TABLE }}
  AIRTABLE_VIEW: ${{ secrets.AIRTABLE_VIEW }}
  TWILIO_FROM: ${{ secrets.TWILIO_FROM }}
  TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
  TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
  S3_BUCKET: city-bureau-chi-covid-chat
  RDS_DB_NAME: ${{ secrets.RDS_DB_NAME }}
  RDS_USERNAME: ${{ secrets.RDS_USERNAME }}
  RDS_PASSWORD: ${{ secrets.RDS_PASSWORD }}
  SNS_EMAIL: ${{ secrets.SNS_EMAIL }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-go@v1
        with:
          go-version: 1.14

      - uses: actions/setup-node@v1
        with:
          node-version: "10.x"

      - run: make format

      - uses: actions-contrib/golangci-lint@v1
        env:
          GOROOT: ""
        with:
          args: "run"

      - run: make test

      - run: make build

      - run: npm install -g serverless

      - run: npm install

      - run: make deploy
